### PR TITLE
Hamburger menu

### PR DESCRIPTION
**Pull request by kamranahmad123**
1. Add hamburger menu button to the project portfolio
2. Add styling and postions to the hamburger menu
3. Modify README.md file

### CODE REVIEW

**Review by emmiiorji — CHANGES_REQUESTED** [review]
Hi @kamranahmad123, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Ouch-gifs-38715704-365-199

You have submitted a project that's not using the [updated readme template](https://github.com/microverseinc/readme-template). Kindly modify your readme file using the newly recommended template. Check the announcement channel on slack for more information about the new template.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by sja-thedude** [comment]
Hi @kamranahmad123 

Your readme is not shown on the branch. Kindly add the updated readme to the branch and not the folder so that it is visible. If you could add in the next 10 mins then I ill proceed else invalidate the project. 

https://user-images.githubusercontent.com/70269507/203625702-bee6d51b-58f3-44e3-9ef1-6ac1c4dc7aec.mov

**Review by sja-thedude — CHANGES_REQUESTED** [review]
Hi @kamranahmad123,

Kindly make sure to add the updated readme to the project from [here](https://github.com/microverseinc/readme-template).

**Comment by kamranahmad123** [comment]
Heo Sayeda juveria,
I did accordingly, please check.
Thanks

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 23, 2022 at 11:23 PM, Syeda Juveria ***@***.***> wrote:   


Hi @kamranahmad123

Your readme is not shown on the branch. Kindly add the updated readme to the branch and not the folder so that it is visible. If you could add in the next 10 mins then I ill proceed else invalidate the project.

https://user-images.githubusercontent.com/70269507/203625702-bee6d51b-58f3-44e3-9ef1-6ac1c4dc7aec.mov

**Comment by sja-thedude** [comment]
> Heo Sayeda juveria, I did accordingly, please check. Thanks Sent from Yahoo Mail on Android On Wed, Nov 23, 2022 at 11:23 PM, Syeda Juveria ***@***.***> wrote: Hi @kamranahmad123 Your readme is not shown on the branch. Kindly add the updated readme to the branch and not the folder so that it is visible. If you could add in the next 10 mins then I ill proceed else invalidate the project. https://user-images.githubusercontent.com/70269507/203625702-bee6d51b-58f3-44e3-9ef1-6ac1c4dc7aec.mov — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Hi @kamranahmad123,  You have to add updated readme. Check [here](https://github.com/kamranahmad123/My_Portfolio_Project/pull/8#pullrequestreview-1192158841)

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Invalid Code Review Request ❌

Hi @kamranahmad123, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't have an updated readme, make sure to add the new one.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by prolajumokeoni** [comment]
Hi @kamranahmad123 and @Yidnekachew-cmd, 
Kindly use the updated version  of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme, this is a requirement to get a review

**Review by nedjwab — APPROVED** [review]
# 🟢 Project Approved! 🏆

## Hi @team   👋

Your project is complete! ✔️ 🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
